### ISSUE TITLE
Do not enable archiving if credentials are empy

### ISSUE THREAD

**Issue by apie** [Crop-R/postgis-wal-g#4]
When using this locally on my machine I dont need the archiving, so I dont set the credentials.

This, however causes postgres to spam me every minute that it is not able to start archiving:

> postgis_1     | 2020-10-21 14:36:30.682 CEST [29] WARNING:  archiving write-ahead log file "00000001000000000000002D" failed too many times, will try again later

It seems that archiving is always enabled, regardless of the credentials:
https://github.com/Crop-R/postgis-wal-g/blob/490b82328ddc880a54d50beb86cf11a9fb618110/initdb/initdb-wal-g.sh#L7

**Comment by damaarten** [comment]
@apie fixed with latest commit. Docker hub images have been auto-rebuilt. https://hub.docker.com/r/dacom1/postgis-wal-g/builds
Give it a try.

**Comment by apie** [comment]
Thank you! I had to pull the new image en remove my volume + container.
